name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        env:
          IMAGE_NAME: your-docker-image-name
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME
          docker push $DOCKER_USERNAME/$IMAGE_NAME

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo $AZURE_CREDENTIALS | base64 --decode > /tmp/credentials.json
          az login --service-principal --username APP_ID --password PASSWORD --tenant TENANT_ID

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          wget https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
          unzip terraform_0.14.7_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -var "client_id=$CLIENT_ID" -var "client_secret=$CLIENT_SECRET" -out=tfplan

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
